[package]
name = "aunema"
version = "0.0.1"
authors = ["enfipy"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
envy = "0.4"
actix-web = "1.0.0-beta.5"
postgres = "0.15.2"

[[bin]]
name = "aunema"
path = "src/main.rs"
