[package]
name = "aunema"
version = "0.0.1"
authors = ["enfipy"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
envy = "0.4"
actix-web = "0.7.19"

[[bin]]
name = "aunema"
path = "src/main.rs"
