version: "3"

networks:
  dev:

volumes:
  data:

services:

  aunema:
    container_name: aunema
    build:
      args:
        PROJECT: aunema
      context: .
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - ./src:/usr/src/aunema/src
    env_file: .env
    environment:
      PRODUCTION: "false"
      SERVER_PORT: 8000
      DB_CONNECTION: "postgresql://root@db:26257"

      STORAGE_AUTH: "./storage/auth"
      STORAGE_TEMPORARY: "./storage/videos/tmp"
      STORAGE_FINISHED: "./storage/videos/fin"
      STORAGE_ELEMENTS: "./storage/videos/elms"
      STORAGE_PRODUCTION: "./storage/videos/prod"
    ports:
      - 8000:8000
    networks:
      - dev
    depends_on:
      - db

  db:
    container_name: db
    image: cockroachdb/cockroach
    command: start --insecure
    volumes:
      - data:/cockroach/cockroach-data
    ports:
      - "8080:8080"
      - "26257:26257"
    logging:
      driver: none
    networks:
      - dev

  migrate:
    container_name: migrate
    image: migrate/migrate
    command: -path /migrations -database cockroachdb://db:26257?sslmode=disable up 1
    volumes:
      - ./migrations:/migrations
    networks:
      - dev
    depends_on:
      - db
